# Generated by Django 4.2.2 on 2023-07-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.departamento', verbose_name='Departamentos Participantes'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone',
            field=models.CharField(max_length=30, verbose_name='Contato(Whats)'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=60, verbose_name='Nome do Funcionário'),
        ),
    ]
