# Generated by Django 4.2.2 on 2023-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='documentos'),
        ),
    ]
