# Generated by Django 4.2.2 on 2023-06-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cidade',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='complemento',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fone',
            field=models.CharField(default='(17) 98118-8163', help_text='Fone/Whatsapp', max_length=30),
            preserve_default=False,
        ),
    ]
