# Generated by Django 4.2.2 on 2023-06-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_departamento_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='encarregado',
            field=models.CharField(blank=True, help_text='Encarregado', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='localizacao',
            field=models.CharField(blank=True, help_text='Localização', max_length=100, null=True),
        ),
    ]
