# Generated by Django 4.2.2 on 2023-07-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_departamento_encarregado_departamento_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='encarregado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
